name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches:
    - '*'
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: usertypeservices
      PROJECT_ID: voicetotext-379213
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v2


      with:
        service_account: 'speechtotext@voicetotext-379213.iam.gserviceaccount.com'
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet


      env:
        GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
        # GIT_TAG: v0.1.0
    - name: Push Docker Image to Artifact Registry
      # - name: Push Docker Image to Artifact Registry voicetotext-379213
      run: "# echo $SRC_IMG_1\n# echo $DEST_IMG_1\n# echo $DEST_IMG_2      \n   #magic___^_^___line\ndocker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest\n# docker image list\ndocker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.0\n# docker image list\ndocker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest\ndocker push gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.0\n   #magic___^_^___line\n   #magic___^_^___line\n   #magic___^_^___line\n   #magic___^_^___line"
      # - name: Push Docker Image to Artifact Registry
#   run: "# echo $SRC_IMG_1\n# echo $DEST_IMG_1\n# echo $DEST_IMG_2      \n   #magic___^_^___line\ndocker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest\n# docker image list\ndocker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.0\n# docker image list\ndocker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest\ndocker push gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.0\n   #magic___^_^___line\n   #magic___^_^___line\n   #magic___^_^___line\n   #magic___^_^___line"
# run: |-
#   echo $GIT_TAG
#   docker tag $IMAGE_NAME:latest us-docker.pkg.dev/voicetotext-379213/gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
#   docker tag $IMAGE_NAME:latest us-docker.pkg.dev/voicetotext-379213/gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.0
#   docker push us-docker.pkg.dev/voicetotext-379213/gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
#   docker push us-docker.pkg.dev/voicetotext-379213/gcr.io/$PROJECT_ID/$IMAGE_NAME:v0.1.0
